name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2

      - name: Install npm dependencies
        run: npm ci

      - name: Install playwright
        run: npx playwright install

      - name: Unit tests
        run: npm run test:cov

      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@0.2.0
        with:
          project-token: ${{ secrets.CODACY_TOKEN }}
